name: Node.js Package Test Publish

on:
  push:
    branches:
      - "develop"
      - "feature/*"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          node-version: 8.9.0
      - run: pnpm install
      - run: pnpm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2
        with:
          node-version: 8.9.0
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm publish --no-git-checks --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
